### ISSUE TITLE
Issue with OKTA in unity + iOS

### ISSUE THREAD

**Issue by arvind-balamurugan** [nickgamb/Okta_Unity#1]
[ErrorLog_OKTA.txt](https://github.com/nickgamb/Okta_Unity/files/5282383/ErrorLog_OKTA.txt)

Please refer to the attached error log files captured for Unity iOS build.

**Comment by nickgamb** [comment]
This example was fairly narrow in scope and expected desktop environments. I assume it works for you when running in editor on Mac/Windows? I will need to go through and test for mobile devices to see what is not supported in these environments and adjust the example code accordingly. If you give me a bit, I will work on that.

**Comment by arvind-balamurugan** [comment]
It did work in windows. For Android and Mac had to specify the UserAgent before calling it. Only for iOS, i am getting this issue.

**Comment by nickgamb** [comment]
Awesome! I will update the code and fully test for mobile builds so that this example is more complete! Thank you for reporting and for pointing me at the primary issue!

**Comment by nickgamb** [comment]
> It did work in windows. For Android and Mac had to specify the UserAgent before calling it. Only for iOS, i am getting this issue.

Would you be willing to share how you specified UserAgent to get it working? I have tried multiple ideas but all I can seem to get is that "One of the identified items was in an invalid format."

**Comment by arvind-balamurugan** [comment]
sure...here you go 
[PanelManager.txt](https://github.com/nickgamb/Okta_Unity/files/5322825/PanelManager.txt)

**Comment by nickgamb** [comment]
Thank you so much. The Okta SDK typically does not require UserAgent to be passed in this way. I sent this along to my SDK team to have them dig into a bit further. For now, I have updated this repo with the fix and credited you. Thank you again!

**Comment by nickgamb** [comment]
@arvind-balamurugan 

We found the issue and how it relates to Unity. 

The Okta SDK calls a Helper class, when creating default headers, that gets the runtime version https://github.com/okta/okta-auth-dotnet/blob/34fbec3d54f2a4f1371a3ec9812af9dccfef9d59/Okta.Sdk.Abstractions/UserAgentBuilder.cs#L47

If we check on what is being returned by this in Unity we get "Mono 5.11.0 ((HEAD/369243a66cf)"
Debug.Log(UserAgentHelper.GetRuntimeVersion());

The problem is the extra (. If you manually pass a UserAgent of "Mono 5.11.0 (HEAD/369243a66cf)" without the extra ( it works fine. If you manually pass a UserAgent of "Mono 5.11.0 ((HEAD/369243a66cf)" it breaks. 

Debug.Log(System.Runtime.InteropServices.RuntimeInformation.OSDescription); returns "Unix 19.6.0.0" which works just fine. 

For now, I have updated the code to pass a custom UserAgent of System.Runtime.InteropServices.RuntimeInformation.OSDescription. This works around the formatting issue.

I have notified our SDK team and we will work to sanitize the string before returning from the helper class in a future build.
